# Generated by Django 6.0 on 2025-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuraRead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocumnet',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='pdfdocumnet',
            name='File',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
